timezone: Asia/Taipei
scope:
  repos:
    - lovemage/RepoDigest
    - lovemage/auraway.org
    - lovemage/morea
providers:
  github:
    tokenEnv: GITHUB_TOKEN
output:
  mode: internal
  target: internal
  lang: en
  tone: calm
  length: short
  include:
    stack: false
    links: true
    metrics: true
