name: Feature Request
description: Suggest a user-facing improvement.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user problem are you trying to solve?
      placeholder: As a user, I want ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe expected behavior and UX.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Optional
  - type: textarea
    id: scope
    attributes:
      label: Scope Impact
      description: Which package areas are involved? (`core`, `cli`, provider, renderer, docs)
  - type: textarea
    id: examples
    attributes:
      label: Example Commands / Output
      render: shell

